Apply shellcheck recommandation on bin/ and libexec

diff --git a/libexec/helpers b/libexec/helpers
--- a/libexec/helpers
+++ b/libexec/helpers
@@ -1,16 +1,16 @@
 #!/usr/bin/env bash
 
 function error_and_die() {
-  echo -e "pkenv: $(basename ${0}): \033[0;31m[ERROR] ${1}\033[0;39m" >&2
+  echo -e "pkenv: $(basename "${0}"): \\033[0;31m[ERROR] ${1}\\033[0;39m" >&2
   exit 1
 }
 
 function warn_and_continue() {
-  echo -e "pkenv: $(basename ${0}): \033[0;33m[WARN] ${1}\033[0;39m" >&2
+  echo -e "pkenv: $(basename "${0}"): \\033[0;33m[WARN] ${1}\\033[0;39m" >&2
 }
 
 function info() {
-  echo -e "\033[0;32m[INFO] ${1}\033[0;39m"
+  echo -e "\\033[0;32m[INFO] ${1}\\033[0;39m"
 }
 
 # Curl wrapper to switch TLS option for each OS
@@ -18,13 +18,14 @@ function curlw() {
   local TLS_OPT="--tlsv1.2"
 
   # Check if curl is 10.12.6 or above
-  if [[ -n "$(command -v sw_vers 2>/dev/null)" && "$(sw_vers)" =~ 10\.12\.([6-9]|[0-9]{2}) ]]; then
+  if [[ -n "$(command -v sw_vers 2>/dev/null)" && "$(sw_vers)" =~ 10\\.12\\.([6-9]|[0-9]{2}) ]]; then
     TLS_OPT=""
   fi
 
   curl ${TLS_OPT} "$@"
 }
 
+# shellcheck disable=SC2034 # Use as sourced function
 function get_version_requested() {
   if [ -z "${1}" ]; then
     version_file="$(pkenv-version-file)"
