Refactor test uninstall command

diff --git a/libexec/pkenv-uninstall b/libexec/pkenv-uninstall
--- a/libexec/pkenv-uninstall
+++ b/libexec/pkenv-uninstall
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 function error_and_die() {
-  echo -e "pkenv: ${0}: ${1}" >&2
+  echo -e "pkenv: $(basename ${0}): \033[0;31m[ERROR] ${1}\033[0;39m" >&2
   exit 1
 }
 
