Adopt tfenv upstream modification

diff --git a/libexec/pkenv-use b/libexec/pkenv-use
--- a/libexec/pkenv-use
+++ b/libexec/pkenv-use
@@ -38,6 +38,6 @@ target_path=${PKENV_ROOT}/versions/${version}
   || error_and_die "Version directory for ${version} is present, but the packer binary is not executable! Manual intervention required. "
 
 info "Switching to v${version}"
-echo "${version}" > "${PKENV_ROOT}/version"
+echo "${version}" > "$(pkenv-version-file)" || error_and_die "'switch to v${version} failed'"
 packer version 1>/dev/null || error_and_die "'packer version' failed. Something is seriously wrong"
 info "Switching completed"
