Fix issue #1 (apply tfenv curl modification )

diff --git a/libexec/pkenv-install b/libexec/pkenv-install
--- a/libexec/pkenv-install
+++ b/libexec/pkenv-install
@@ -1,19 +1,7 @@
 #!/usr/bin/env bash
 
-function error_and_die() {
-  echo -e "pkenv: $(basename ${0}): \033[0;31m[ERROR] ${1}\033[0;39m" >&2
-  exit 1
-}
-
-function warn_and_continue() {
-  echo -e "pkenv: $(basename ${0}): \033[0;33m[WARN] ${1}\033[0;39m" >&2
-}
-
-function info() {
-  echo -e "\033[0;32m[INFO] ${1}\033[0;39m"
-}
-
 [ -n "${PKENV_DEBUG}" ] && set -x
+source ${PKENV_ROOT}/libexec/helpers
 
 [ "${#}" -gt 1 ] && error_and_die "usage: pkenv install [<version>]"
 
@@ -36,7 +24,7 @@ elif [[ "${version_requested}" =~ ^latest$ ]]; then
   regex=""
 else
   version="${version_requested}"
-  regex="${version_requested}"
+  regex="^${version_requested}$"
 fi
 
 [ -n "${version}" ] || error_and_die "Version is not specified"
@@ -49,15 +37,16 @@ if [ -f "${dst_path}/packer" ]; then
   exit 0
 fi
 
+PKENV_ARCH=${PKENV_ARCH:-amd64}
 case "$(uname -s)" in
   Darwin*)
-    os="darwin_amd64"
+    os="darwin_${PKENV_ARCH}"
     ;;
   MINGW64*)
-    os="windows_amd64"
+    os="windows_${PKENV_ARCH}"
     ;;
   *)
-    os="linux_amd64"
+    os="linux_${PKENV_ARCH}"
     ;;
 esac
 
@@ -76,9 +65,9 @@ download_tmp="$(mktemp -d pkenv_download.XXXXXX)" || error_and_die "Unable to cr
 trap "rm -rf ${download_tmp}" EXIT;
 
 info "Downloading release tarball from ${version_url}/${tarball_name}"
-curl -# --tlsv1.2 -f -o "${download_tmp}/${tarball_name}" "${version_url}/${tarball_name}" || error_and_die "Tarball download failed"
+curlw -# -f -o "${download_tmp}/${tarball_name}" "${version_url}/${tarball_name}" || error_and_die "Tarball download failed"
 info "Downloading SHA hash file from ${version_url}/${shasums_name}"
-curl -s --tlsv1.2 -f -o "${download_tmp}/${shasums_name}" "${version_url}/${shasums_name}" || error_and_die "SHA256 hashes download failed"
+curlw -s -f -o "${download_tmp}/${shasums_name}" "${version_url}/${shasums_name}" || error_and_die "SHA256 hashes download failed"
 
 # Verify signature if keybase is present.
 if [[ -n "${keybase_bin}" && -x "${keybase_bin}" ]]; then
@@ -91,7 +80,7 @@ if [[ -n "${keybase_bin}" && -x "${keybase_bin}" ]]; then
     warn_and_continue "Unable to verify GPG signature unless logged into keybase and following hashicorp"
   else
     info "Downloading SHA hash signature file from ${version_url}/${shasums_name}.sig"
-    curl -s --tlsv1.2 -f -o "${download_tmp}/${shasums_name}.sig" "${version_url}/${shasums_name}.sig" || error_and_die "SHA256SUMS signature download failed"
+    curlw -s -f -o "${download_tmp}/${shasums_name}.sig" "${version_url}/${shasums_name}.sig" || error_and_die "SHA256SUMS signature download failed"
     "${keybase_bin}" pgp verify -S hashicorp -d "${download_tmp}/${shasums_name}.sig" -i "${download_tmp}/${shasums_name}" || error_and_die "SHA256SUMS signature does not match!"
   fi
 else
@@ -113,3 +102,4 @@ mkdir -p "${dst_path}" || error_and_die "Failed to make directory ${dst_path}"
 unzip "${download_tmp}/${tarball_name}" -d "${dst_path}" || error_and_die "Tarball unzip failed"
 
 info "Installation of packer v${version} successful"
+pkenv-use "$version"
